version: '3.8'

services:
  front:
    container_name: front
    build: .
    volumes: 
      - ./:/app
    ports:
      - 8080:3000
    restart: always
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=8080
      - CHOKIDIRUSEPOLLING=true
    command: sh -c "npm install && npx nodemon"
